[[pages]]
path = "메인.py"
name = "메인"
icon = "🌲"

[[pages]]
path = "사용자입력.py"
name = "사용자입력"
icon = "📝"

[[pages]]
path = "식물.py"
name = "꽃가루 알러지와 식물 정보"
icon = "🌿"

[[pages]]
path = "절지동물.py"
name = "절지동물"
icon = "🕷️"

[[pages]]
path = "병원.py"
name = "병원"
icon = "🏥"
